=== api-evangelist/weather-gov/json-schema/weather-gov-alert-atom-entry-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weather-gov/refs/heads/main/json-schema/weather-gov-alert-atom-entry-schema.json",
  "title": "AlertAtomEntry",
  "description": "An alert entry in an Atom feed",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "xml": {
        "namespace": "http://www.w3.org/2005/Atom"
      }
    },
    "updated": {
      "type": "string",
      "xml": {
        "namespace": "http://www.w3.org/2005/Atom"
      }
    },
    "published": {
      "type": "string",
      "xml": {
        "namespace": "http://www.w3.org/2005/Atom"
      }
    },
    "author": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2005/Atom"
      }
    },
    "summary": {
      "type": "string",
      "xml": {
        "namespace": "http://www.w3.org/2005/Atom"
      }
    },
    "event": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "sent": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "effective": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "expires": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "status": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "msgType": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "category": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "urgency": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "severity": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "certainty": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "areaDesc": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "polygon": {
      "type": "string",
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "geocode": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/AlertXMLParameter"
      },
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    },
    "parameter": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/AlertXMLParameter"
      },
      "xml": {
        "namespace": "urn:oasis:names:tc:emergency:cap:1.2"
      }
    }
  }
}

=== api-evangelist/weather-gov/examples/weather-gov-alert-atom-entry-example.json
{
  "id": "example-value",
  "updated": "example-value",
  "published": "example-value",
  "author": {
    "name": "Example Name"
  },
  "summary": "example-value",
  "event": "Winter Storm Warning",
  "sent": "example-value",
  "effective": "example-value",
  "expires": "example-value",
  "status": "active",
  "msgType": "land",
  "category": "example-value",
  "urgency": "Expected",
  "severity": "Moderate",
  "certainty": "Likely",
  "areaDesc": "example-value",
  "polygon": "example-value",
  "geocode": [
    null
  ],
  "parameter": [
    null
  ]
}
