=== api-evangelist/weather-gov/json-schema/weather-gov-observation-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weather-gov/refs/heads/main/json-schema/weather-gov-observation-schema.json",
  "title": "Observation",
  "description": "Observation schema from weather.gov API",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "#/components/schemas/JsonLdContext"
    },
    "geometry": {
      "$ref": "#/components/schemas/GeometryString"
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "enum": [
        "wx:ObservationStation"
      ],
      "type": "string"
    },
    "elevation": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "station": {
      "type": "string",
      "format": "uri"
    },
    "stationId": {
      "type": "string"
    },
    "stationName": {
      "type": "string"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "rawMessage": {
      "type": "string"
    },
    "textDescription": {
      "type": "string"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": true
    },
    "presentWeather": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/MetarPhenomenon"
      }
    },
    "temperature": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "dewpoint": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "windDirection": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "windSpeed": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "windGust": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "barometricPressure": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "seaLevelPressure": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "visibility": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "maxTemperatureLast24Hours": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "minTemperatureLast24Hours": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "precipitationLastHour": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "precipitationLast3Hours": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "precipitationLast6Hours": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "relativeHumidity": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "windChill": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "heatIndex": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "cloudLayers": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "required": [
          "base",
          "amount"
        ],
        "type": "object",
        "properties": {
          "base": {
            "$ref": "#/components/schemas/QuantitativeValue"
          },
          "amount": {
            "$ref": "#/components/schemas/MetarSkyCoverage"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== api-evangelist/weather-gov/examples/weather-gov-observation-example.json
{
  "@id": "https://api.weather.gov/resource/example",
  "@type": "wx:ObservationStation",
  "station": "https://api.weather.gov/resource/example",
  "stationId": "KTOP",
  "stationName": "KTOP",
  "timestamp": "2026-05-03T14:30:00Z",
  "rawMessage": "Example weather description text.",
  "textDescription": "Example weather description text.",
  "presentWeather": [
    null
  ]
}
