=== api-evangelist/weather-gov/json-schema/weather-gov-observation-station-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weather-gov/refs/heads/main/json-schema/weather-gov-observation-station-schema.json",
  "title": "ObservationStation",
  "description": "ObservationStation schema from weather.gov API",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "#/components/schemas/JsonLdContext"
    },
    "geometry": {
      "$ref": "#/components/schemas/GeometryString"
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "enum": [
        "wx:ObservationStation"
      ],
      "type": "string"
    },
    "elevation": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "stationIdentifier": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "timeZone": {
      "type": "string",
      "format": "iana-time-zone-identifier"
    },
    "provider": {
      "type": "string",
      "description": "The data provider for this station. E.g., \"ASOS,\" \"MesoWest,\" etc."
    },
    "subProvider": {
      "type": "string",
      "description": "The sub-provider of for this station. E.g., \"FAA,\" \"DOT,\" etc."
    },
    "forecast": {
      "type": "string",
      "description": "A link to the NWS public forecast zone containing this station.",
      "format": "uri"
    },
    "county": {
      "type": "string",
      "description": "A link to the NWS county zone containing this station.",
      "format": "uri"
    },
    "fireWeatherZone": {
      "type": "string",
      "description": "A link to the NWS fire weather forecast zone containing this station.",
      "format": "uri"
    },
    "distance": {
      "$ref": "#/components/schemas/QuantitativeValue"
    },
    "bearing": {
      "$ref": "#/components/schemas/QuantitativeValue"
    }
  },
  "additionalProperties": false
}

=== api-evangelist/weather-gov/examples/weather-gov-observation-station-example.json
{
  "@id": "https://api.weather.gov/resource/example",
  "@type": "wx:ObservationStation",
  "stationIdentifier": "KTOP",
  "name": "Example Name",
  "timeZone": "NWZ001",
  "provider": "example-value",
  "subProvider": "example-value",
  "forecast": "https://api.weather.gov/resource/example",
  "county": "https://api.weather.gov/resource/example",
  "fireWeatherZone": "https://api.weather.gov/resource/example"
}
